# Generated by Django 2.2.16 on 2020-09-07 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('func_crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crud',
            old_name='body',
            new_name='description',
        ),
    ]
